# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contemplatio',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lectio',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meditatio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='oratio',
        ),
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='external_author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
    ]
