# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171223_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='external_author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
