# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171224_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='external_author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ExternalAuthor'),
        ),
    ]
