# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171230_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='image_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
