# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7),
        ),
    ]
