# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180215_0155'),
        ('blog', '0014_auto_20180215_0202'),
    ]

    operations = [
    ]
