# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180215_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.CharField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일'), (7, '해당없음')], default=7, max_length=1),
        ),
    ]
