# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_merge_20180215_0207'),
        ('blog', '0016_auto_20180215_0209'),
    ]

    operations = [
    ]
